language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: jZFsxkA73TFnJlleAh+wAncHu9NJtdZVVjaEVofhRv1apUGPtAjgOCwCNUeD42dyT0+4GHfWO1lK8qTh2zdpdkfD3QsUpimq/wG4y0kcHGys/npq3y6yMc4gFV7YImqcnx6fpWqbB1l1RmsoHiqo45mSxYJojtqTCFsU+yIrNeuk5T8VY7feTPQAFZU4KTsYCKdxGIMhZydFCDt3NE0F48ktxL8fKCB2DBt/X0AjWA3sv5B/N611kVhUo8r9Q1KSYY/Ddp5J72eRm9jegiFYhoHobRHKMMcDlLiWP2Q5rK3AlGFkeZt6mRO0lEjEBBiaQbkhBYS1LT8s8vlEtj+uQ+VSMwRO1BUgYLrjnQ2KghhOr21vI2MmlUcoFTllv1Eczc8sFpA/RTuLm02TxXKwPwkkHaC7XtJ7EGZjeYlWdI/pSih+UZ7c8ueNN10GYuMvzVDWWdwgDU/4JWXJQBDOU94naixzy0jH3hkwQEnwMaTfSVuuqEoMNNkeWYJPjDCg3bWmAT2UkyYFtaeQacL4LtCkDhbJAiJYVCGu8kjF2Fb5a0cDfXYAkYlw/gvnqTofQqhsEuHpSbnXtQD/zsEfAVMm++7Rdn8icAyfk6T8rnVJ/Ocid472lv4S7n04H6GmJSyMJdhIRuLrbhZZKMTT8bEcqtKkzrXrm8jzKNI23r8=
