language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: vdS8ldlQOoMZFgPLNvjw8lsoqweLN75eouC9n4VKPjEEmWsJn5qicNuhRj/57sj8H1BZfOdipJTiRCdl1zlD0U7st0dpNILkuDpHkLFN22P6KSCdTgC+I585NuOj7NnZIc//7vQAMzvhPwh8+lfrKEVFiaRbGtvGZIw4EluRERDucIZb0CEqU6u7uy4V3YNI3BXMKDg678qwJO08lpvdBd2cXc6UaH0lIKHygXp3w/BLr9E8oI7ksg9mjxb44nfoWiBng9BVwgV5DDdF+DUeqEykyAGcY1615PwZ78t2LHINctctF64hxM22cmK3U//akKzXpN5uqZLnPYbjO4Kv/iEvwRdNb1xvlGvzBiIKxHTR/ikbJKfRTJiBcwwe5ADKAzg0puP2y7+fnG7ZJlb9JjP5LL6VsI3oJ+f0ywkUuE1nESgU/Ob5VyS5nCLVb9bRSDJlcmaWPJfQTxiYh79xmq2nbEQJsqLkgopd2EYtofryXrIigwfFntwevXxoGOXAboGplU7fT+bUHo55ykTQl4eY+ACgfO0RBn6iLB2ImGwot9c3uHr2z+sYr9YNzGUSvZAxrvDklvc7cUzGYbwQ1TaIB0W8IDK/mfxZw7owwd0Vl11HVwCSmNqpBuvkwczfWl6neUGRD7hm2RlKI/GrwE2IgSBRVKmKlK59TtlGmxM=
