language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  secret_access_key:
    secure: kaPv2ueGQ0MdnqpfVLrIxwbUYCwF4Kq3Ng0MgwJZjFOlXJk/N8SI97IGg2ztOzLh/yeEJfKNaGl41YY5OwF4/g5kALmoz0ozWBg65pruokKdEFXujTmuLYJQ38gE+CyauCT5uQDrZrd1rhyraERW1OePr4PHoN3FENeH2b8uRK0JN13MJceWEGbZUPwvpAIkkD6hHcm/PqjY8yFi+++T+P70jinXViKgGH+yCAqyoH7T7NzSpu3yK/c2dom8T1bAQ2gqYlF1CTac8RQyWYh5nhKfQEZBTbH82TY4pZ20A1N1NssKcXdtPvdxS0miCoMFSAFU22DBnqZFS3zAgpLiTlxRSrzeHX+EV7NEmwT6RgxVB28G8WygyLofpEzpqJDE5SvPXHcE3aTbsBy/UN3MjqRjCtHWpnccVhCmhqyDZHB30XzBd8QUbix9+GSo7H2mEfmUy6ImsMpyhfJweHdmcZ4DDdZcZwdWWsSH92h345OiDucns5PHC3KynAeBfGNlEBL7gmjuURhaIS6OZAFpA1xo2T7WZsfDfZ4cURCkogF6R4Nlh24EIvaTfKg7duhQT0rdmN5I1IPTT96uWyukJdI2dLainKphJ3nUshGnh4eBYpcPNQFGsJSvwaCe5cpRb0qWKyGYZd0s4csKFQoG4OOk7bK+22Pq7Zq6ohKIjAg=
